import {useEffect,useState} from 'react';
import {request,post} from './api';
type Batch={id:string;project:string|null;destination:string;state:string;completed:number;failed:number;total:number;current_title?:string;error?:string};
const names:Record<string,string>={planning:'发现工作区',active:'等待处理',indexing:'同步本地库',syncing:'同步服务器',succeeded:'已完成',completed_with_errors:'部分失败',failed:'失败',paused:'已暂停',cancelled:'已取消'};
export async function startWorkspaceBatch(project:string|null,destination='local'){return post('/source-batches',{project,destination})}
export function BatchProgress({signal=0,onError}:{signal?:number;onError:(e:unknown)=>void}){
  const [items,setItems]=useState<Batch[]>([]),[details,setDetails]=useState<string|null>(null),[rows,setRows]=useState<any[]>([]),[next,setNext]=useState<string|null>(null);
  useEffect(()=>{let live=true;let timer:ReturnType<typeof setTimeout>;async function load(){try{const data=await request<{items:Batch[]}>('/source-batches');if(live)setItems(data.items||[])}catch(e){if(live)onError(e)}finally{if(live)timer=setTimeout(()=>void load(),2000)}}void load();return()=>{live=false;clearTimeout(timer)}},[signal]);
  async function action(id:string,value:string){try{await request('/source-batches/'+id,{method:'PATCH',body:JSON.stringify({action:value})});setItems((await request<{items:Batch[]}>('/source-batches')).items)}catch(e){onError(e)}}
  async function inspect(id:string,cursor=''){try{const result=await request<{items:any[];next_cursor:string|null}>('/source-batches/'+id+'/items?cursor='+encodeURIComponent(cursor));setDetails(id);setRows(old=>cursor?[...old,...result.items]:result.items);setNext(result.next_cursor)}catch(e){onError(e)}}
  if(!items.length)return null;
  return <section className="batch-progress" aria-label="工作区批次进度">{items.slice(0,1).map(item=><div className="batch-row" data-state={item.state} key={item.id}><strong>{item.project?.split(/[\\/]/).pop()||'工作区同步'}</strong><span>{names[item.state]||item.state} · {item.completed}/{item.total}{item.failed?` · ${item.failed} 失败`:''}</span><small>{item.current_title||item.error|| (item.destination==='server'?'团队服务器':'本地库')}</small><div>{['planning','active','indexing','syncing'].includes(item.state)&&<button onClick={()=>void action(item.id,'pause')}>暂停</button>}{item.state==='paused'&&<button onClick={()=>void action(item.id,'resume')}>继续</button>}{['failed','completed_with_errors'].includes(item.state)&&<button onClick={()=>void action(item.id,'retry')}>重试失败项</button>}{['planning','active','indexing','syncing','paused'].includes(item.state)&&<button onClick={()=>void action(item.id,'cancel')}>取消批次</button>}<button onClick={()=>void inspect(item.id)}>明细</button></div></div>)}{details&&<div className="batch-details"><button onClick={()=>setDetails(null)}>收起明细</button>{rows.map(row=><p key={row.id}>{row.title} · {names[row.state]||row.state}{row.error?' · '+row.error:''}</p>)}{next&&<button onClick={()=>void inspect(details,next)}>更多</button>}</div>}</section>;
}
